/// A single interview question generated by the backend.

/// Type classification for interview questions.
enum QuestionType {
  technical,
  behavioral,
  hr,
  project,
  followUp;

  String get displayName {
    switch (this) {
      case QuestionType.technical:
        return 'Technical';
      case QuestionType.behavioral:
        return 'Behavioral';
      case QuestionType.hr:
        return 'HR';
      case QuestionType.project:
        return 'Project';
      case QuestionType.followUp:
        return 'Follow-up';
    }
  }

  static QuestionType fromString(String value) {
    switch (value.toLowerCase().replaceAll('_', '')) {
      case 'technical':
        return QuestionType.technical;
      case 'behavioral':
        return QuestionType.behavioral;
      case 'hr':
        return QuestionType.hr;
      case 'project':
        return QuestionType.project;
      case 'followup':
      case 'follow_up':
        return QuestionType.followUp;
      default:
        return QuestionType.technical;
    }
  }
}

/// Represents a single interview question.
class InterviewQuestion {
  final String question;
  final QuestionType type;
  final String source;
  final bool isFollowUp;

  const InterviewQuestion({
    required this.question,
    required this.type,
    this.source = '',
    this.isFollowUp = false,
  });

  factory InterviewQuestion.fromJson(Map<String, dynamic> json) {
    return InterviewQuestion(
      question: json['question']?.toString() ?? '',
      type: QuestionType.fromString(json['question_type']?.toString() ?? 'technical'),
      source: json['source']?.toString() ?? '',
      isFollowUp: json['is_follow_up'] == true,
    );
  }

  Map<String, dynamic> toJson() => {
    'question': question,
    'question_type': type.name,
    'source': source,
    'is_follow_up': isFollowUp,
  };

  Map<String, dynamic> toFirestoreMap() => toJson();

  factory InterviewQuestion.fromFirestore(Map<String, dynamic> data) {
    return InterviewQuestion.fromJson(data);
  }

  InterviewQuestion asFollowUp() {
    return InterviewQuestion(
      question: question,
      type: QuestionType.followUp,
      source: source,
      isFollowUp: true,
    );
  }
}
